// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBchaQytIFakEt8yPILugElzzdbM0ZCgRY',
    appId: '1:494650703271:web:2637855bf4b7b0ea514a82',
    messagingSenderId: '494650703271',
    projectId: 'chicken-kitchen-b7b09',
    authDomain: 'chicken-kitchen-b7b09.firebaseapp.com',
    storageBucket: 'chicken-kitchen-b7b09.firebasestorage.app',
    measurementId: 'G-PL98KELQ16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAKFJd25KQFgn1dGlZ8zPrMLu9eF0QF8Q',
    appId: '1:494650703271:android:77cf1545edf8421b514a82',
    messagingSenderId: '494650703271',
    projectId: 'chicken-kitchen-b7b09',
    storageBucket: 'chicken-kitchen-b7b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxVIQ0omwAOvDKFzvw2izYt3qfZmne1ms',
    appId: '1:494650703271:ios:9d5703fdf391f175514a82',
    messagingSenderId: '494650703271',
    projectId: 'chicken-kitchen-b7b09',
    storageBucket: 'chicken-kitchen-b7b09.firebasestorage.app',
    androidClientId: '494650703271-0j8el2g8ri5dvsp192s5erp4uupons36.apps.googleusercontent.com',
    iosClientId: '494650703271-7lejpobkb0ictqi2snk6d6afk8cijvde.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobiletest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxVIQ0omwAOvDKFzvw2izYt3qfZmne1ms',
    appId: '1:494650703271:ios:9d5703fdf391f175514a82',
    messagingSenderId: '494650703271',
    projectId: 'chicken-kitchen-b7b09',
    storageBucket: 'chicken-kitchen-b7b09.firebasestorage.app',
    androidClientId: '494650703271-0j8el2g8ri5dvsp192s5erp4uupons36.apps.googleusercontent.com',
    iosClientId: '494650703271-7lejpobkb0ictqi2snk6d6afk8cijvde.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobiletest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBchaQytIFakEt8yPILugElzzdbM0ZCgRY',
    appId: '1:494650703271:web:ef869fb3f26201cc514a82',
    messagingSenderId: '494650703271',
    projectId: 'chicken-kitchen-b7b09',
    authDomain: 'chicken-kitchen-b7b09.firebaseapp.com',
    storageBucket: 'chicken-kitchen-b7b09.firebasestorage.app',
    measurementId: 'G-ZYBYNRPZ5R',
  );

}